const GAME_SOCKET_API_PATH = "ws://localhost:8000/ws/lobby/";

const MT_RESPONSE_COMMAND_SERVER_RESPONSE = "server_response";
const MT_RESPONSE_DICE_ROLLS_RESPONSE = "dice_rolls_response";
const MT_RESPONSE_BEGIN_TURN_RESPONSE = "begin_turn_response";
const MT_RESPONSE_PLAYERS_STATUS_UPDATE = "player_status_update_response";

export default {
  MT_RESPONSE_COMMAND_SERVER_RESPONSE,
  MT_RESPONSE_DICE_ROLLS_RESPONSE,
  MT_RESPONSE_BEGIN_TURN_RESPONSE,
  MT_RESPONSE_PLAYERS_STATUS_UPDATE,

  GAME_SOCKET_API_PATH
};
