# Generated by Django 3.0.2 on 2020-02-21 21:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=30, unique=True)),
                ('game_status', models.CharField(choices=[('1', 'Game-Over'), ('0', 'Game-Cancelled'), ('2', 'In-Progress')], max_length=1)),
                ('first_winner', models.IntegerField(null=True)),
                ('second_winner', models.IntegerField(null=True)),
                ('third_winner', models.IntegerField(null=True)),
                ('fourth_winner', models.IntegerField(null=True)),
                ('fifth_winner', models.IntegerField(null=True)),
                ('sixth_winner', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=30)),
                ('board', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('online', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card1_swept', models.CharField(choices=[('00', 'No Card'), ('01', 'Acid Attack'), ('02', 'Alien Metabolism'), ('03', 'Alpha Monster'), ('04', 'Apartment Building'), ('05', 'Armor Plating'), ('06', 'Background Dweller'), ('07', 'Burrowing'), ('08', 'Camouflage'), ('09', 'Commuter Train'), ('10', 'Complete Destruction'), ('11', 'Corner Store'), ('12', 'Dedicated News Team'), ('13', 'Drop from High Altitude'), ('14', 'Eater of the Dead'), ('15', 'Energize'), ('16', 'Energy Hoarder'), ('17', 'Evacuation Orders (x2)'), ('18', 'Even Bigger'), ('19', 'Extra Head(x2)'), ('20', 'Fire Blast'), ('21', 'Fire Breathing'), ('22', 'Freeze Time'), ('23', 'Frenzy'), ('24', 'Friend of Children'), ('25', 'Gas Refinery'), ('26', 'Giant Brain'), ('27', 'Gourmet'), ('28', 'Heal'), ('29', 'Healing Ray'), ('30', 'Herbivore'), ('31', 'Herd Culler'), ('32', 'High Altitude Bombing'), ('33', 'It Has a Child'), ('34', 'Jet Fighters'), ('35', 'Jets'), ('36', 'Made in a Lab'), ('37', 'Metamorph'), ('38', 'Mimic'), ('39', 'Monster Batteries'), ('40', 'National Guard'), ('41', 'Nova Breath'), ('42', 'Nuclear Power Plant'), ('43', 'Omnivore'), ('44', 'Opportunist'), ('45', 'Parasitic Tentacles'), ('46', 'Plot Twist'), ('47', 'Poison Quills'), ('48', 'Poison Spit'), ('49', 'Psychic Probe'), ('50', 'Rapid Healing'), ('51', 'Regeneration'), ('52', 'Rooting for the Underdog'), ('53', 'Shrink Ray'), ('54', 'Skyscraper'), ('55', 'Smoke Cloud'), ('56', 'Solar Powered'), ('57', 'Spiked Tail'), ('58', 'Stretchy'), ('59', 'Tanks'), ('60', 'Telepath'), ('61', 'Urbavore'), ('62', 'Vast Storm'), ('63', 'We are Only Making It Stronger'), ('64', 'Wings'), ('65', 'Amusement Park'), ('66', 'Army'), ('67', 'Cannibalistic'), ('68', 'Intimidating Roar'), ('69', 'Monster Sidekick'), ('70', 'Reflective Hide'), ('71', 'Sleep Walker'), ('72', 'Super Jump'), ('73', 'Throw a Tanker'), ('74', 'Thunder Stomp'), ('75', 'Unstable DNA')], max_length=2)),
                ('card1_swept_type', models.CharField(choices=[('1', 'KEEP'), ('0', 'DISCARD')], max_length=1)),
                ('card2_swept', models.CharField(choices=[('00', 'No Card'), ('01', 'Acid Attack'), ('02', 'Alien Metabolism'), ('03', 'Alpha Monster'), ('04', 'Apartment Building'), ('05', 'Armor Plating'), ('06', 'Background Dweller'), ('07', 'Burrowing'), ('08', 'Camouflage'), ('09', 'Commuter Train'), ('10', 'Complete Destruction'), ('11', 'Corner Store'), ('12', 'Dedicated News Team'), ('13', 'Drop from High Altitude'), ('14', 'Eater of the Dead'), ('15', 'Energize'), ('16', 'Energy Hoarder'), ('17', 'Evacuation Orders (x2)'), ('18', 'Even Bigger'), ('19', 'Extra Head(x2)'), ('20', 'Fire Blast'), ('21', 'Fire Breathing'), ('22', 'Freeze Time'), ('23', 'Frenzy'), ('24', 'Friend of Children'), ('25', 'Gas Refinery'), ('26', 'Giant Brain'), ('27', 'Gourmet'), ('28', 'Heal'), ('29', 'Healing Ray'), ('30', 'Herbivore'), ('31', 'Herd Culler'), ('32', 'High Altitude Bombing'), ('33', 'It Has a Child'), ('34', 'Jet Fighters'), ('35', 'Jets'), ('36', 'Made in a Lab'), ('37', 'Metamorph'), ('38', 'Mimic'), ('39', 'Monster Batteries'), ('40', 'National Guard'), ('41', 'Nova Breath'), ('42', 'Nuclear Power Plant'), ('43', 'Omnivore'), ('44', 'Opportunist'), ('45', 'Parasitic Tentacles'), ('46', 'Plot Twist'), ('47', 'Poison Quills'), ('48', 'Poison Spit'), ('49', 'Psychic Probe'), ('50', 'Rapid Healing'), ('51', 'Regeneration'), ('52', 'Rooting for the Underdog'), ('53', 'Shrink Ray'), ('54', 'Skyscraper'), ('55', 'Smoke Cloud'), ('56', 'Solar Powered'), ('57', 'Spiked Tail'), ('58', 'Stretchy'), ('59', 'Tanks'), ('60', 'Telepath'), ('61', 'Urbavore'), ('62', 'Vast Storm'), ('63', 'We are Only Making It Stronger'), ('64', 'Wings'), ('65', 'Amusement Park'), ('66', 'Army'), ('67', 'Cannibalistic'), ('68', 'Intimidating Roar'), ('69', 'Monster Sidekick'), ('70', 'Reflective Hide'), ('71', 'Sleep Walker'), ('72', 'Super Jump'), ('73', 'Throw a Tanker'), ('74', 'Thunder Stomp'), ('75', 'Unstable DNA')], max_length=2)),
                ('card2_swept_type', models.CharField(choices=[('1', 'KEEP'), ('0', 'DISCARD')], max_length=1)),
                ('card3_swept', models.CharField(choices=[('00', 'No Card'), ('01', 'Acid Attack'), ('02', 'Alien Metabolism'), ('03', 'Alpha Monster'), ('04', 'Apartment Building'), ('05', 'Armor Plating'), ('06', 'Background Dweller'), ('07', 'Burrowing'), ('08', 'Camouflage'), ('09', 'Commuter Train'), ('10', 'Complete Destruction'), ('11', 'Corner Store'), ('12', 'Dedicated News Team'), ('13', 'Drop from High Altitude'), ('14', 'Eater of the Dead'), ('15', 'Energize'), ('16', 'Energy Hoarder'), ('17', 'Evacuation Orders (x2)'), ('18', 'Even Bigger'), ('19', 'Extra Head(x2)'), ('20', 'Fire Blast'), ('21', 'Fire Breathing'), ('22', 'Freeze Time'), ('23', 'Frenzy'), ('24', 'Friend of Children'), ('25', 'Gas Refinery'), ('26', 'Giant Brain'), ('27', 'Gourmet'), ('28', 'Heal'), ('29', 'Healing Ray'), ('30', 'Herbivore'), ('31', 'Herd Culler'), ('32', 'High Altitude Bombing'), ('33', 'It Has a Child'), ('34', 'Jet Fighters'), ('35', 'Jets'), ('36', 'Made in a Lab'), ('37', 'Metamorph'), ('38', 'Mimic'), ('39', 'Monster Batteries'), ('40', 'National Guard'), ('41', 'Nova Breath'), ('42', 'Nuclear Power Plant'), ('43', 'Omnivore'), ('44', 'Opportunist'), ('45', 'Parasitic Tentacles'), ('46', 'Plot Twist'), ('47', 'Poison Quills'), ('48', 'Poison Spit'), ('49', 'Psychic Probe'), ('50', 'Rapid Healing'), ('51', 'Regeneration'), ('52', 'Rooting for the Underdog'), ('53', 'Shrink Ray'), ('54', 'Skyscraper'), ('55', 'Smoke Cloud'), ('56', 'Solar Powered'), ('57', 'Spiked Tail'), ('58', 'Stretchy'), ('59', 'Tanks'), ('60', 'Telepath'), ('61', 'Urbavore'), ('62', 'Vast Storm'), ('63', 'We are Only Making It Stronger'), ('64', 'Wings'), ('65', 'Amusement Park'), ('66', 'Army'), ('67', 'Cannibalistic'), ('68', 'Intimidating Roar'), ('69', 'Monster Sidekick'), ('70', 'Reflective Hide'), ('71', 'Sleep Walker'), ('72', 'Super Jump'), ('73', 'Throw a Tanker'), ('74', 'Thunder Stomp'), ('75', 'Unstable DNA')], max_length=2)),
                ('card3_swept_type', models.CharField(choices=[('1', 'KEEP'), ('0', 'DISCARD')], max_length=1)),
                ('card_purchased', models.CharField(choices=[('00', 'No Card'), ('01', 'Acid Attack'), ('02', 'Alien Metabolism'), ('03', 'Alpha Monster'), ('04', 'Apartment Building'), ('05', 'Armor Plating'), ('06', 'Background Dweller'), ('07', 'Burrowing'), ('08', 'Camouflage'), ('09', 'Commuter Train'), ('10', 'Complete Destruction'), ('11', 'Corner Store'), ('12', 'Dedicated News Team'), ('13', 'Drop from High Altitude'), ('14', 'Eater of the Dead'), ('15', 'Energize'), ('16', 'Energy Hoarder'), ('17', 'Evacuation Orders (x2)'), ('18', 'Even Bigger'), ('19', 'Extra Head(x2)'), ('20', 'Fire Blast'), ('21', 'Fire Breathing'), ('22', 'Freeze Time'), ('23', 'Frenzy'), ('24', 'Friend of Children'), ('25', 'Gas Refinery'), ('26', 'Giant Brain'), ('27', 'Gourmet'), ('28', 'Heal'), ('29', 'Healing Ray'), ('30', 'Herbivore'), ('31', 'Herd Culler'), ('32', 'High Altitude Bombing'), ('33', 'It Has a Child'), ('34', 'Jet Fighters'), ('35', 'Jets'), ('36', 'Made in a Lab'), ('37', 'Metamorph'), ('38', 'Mimic'), ('39', 'Monster Batteries'), ('40', 'National Guard'), ('41', 'Nova Breath'), ('42', 'Nuclear Power Plant'), ('43', 'Omnivore'), ('44', 'Opportunist'), ('45', 'Parasitic Tentacles'), ('46', 'Plot Twist'), ('47', 'Poison Quills'), ('48', 'Poison Spit'), ('49', 'Psychic Probe'), ('50', 'Rapid Healing'), ('51', 'Regeneration'), ('52', 'Rooting for the Underdog'), ('53', 'Shrink Ray'), ('54', 'Skyscraper'), ('55', 'Smoke Cloud'), ('56', 'Solar Powered'), ('57', 'Spiked Tail'), ('58', 'Stretchy'), ('59', 'Tanks'), ('60', 'Telepath'), ('61', 'Urbavore'), ('62', 'Vast Storm'), ('63', 'We are Only Making It Stronger'), ('64', 'Wings'), ('65', 'Amusement Park'), ('66', 'Army'), ('67', 'Cannibalistic'), ('68', 'Intimidating Roar'), ('69', 'Monster Sidekick'), ('70', 'Reflective Hide'), ('71', 'Sleep Walker'), ('72', 'Super Jump'), ('73', 'Throw a Tanker'), ('74', 'Thunder Stomp'), ('75', 'Unstable DNA')], max_length=2)),
                ('card_purchased_type', models.CharField(choices=[('1', 'KEEP'), ('0', 'DISCARD')], max_length=1)),
                ('card_used', models.CharField(choices=[('00', 'No Card'), ('01', 'Acid Attack'), ('02', 'Alien Metabolism'), ('03', 'Alpha Monster'), ('04', 'Apartment Building'), ('05', 'Armor Plating'), ('06', 'Background Dweller'), ('07', 'Burrowing'), ('08', 'Camouflage'), ('09', 'Commuter Train'), ('10', 'Complete Destruction'), ('11', 'Corner Store'), ('12', 'Dedicated News Team'), ('13', 'Drop from High Altitude'), ('14', 'Eater of the Dead'), ('15', 'Energize'), ('16', 'Energy Hoarder'), ('17', 'Evacuation Orders (x2)'), ('18', 'Even Bigger'), ('19', 'Extra Head(x2)'), ('20', 'Fire Blast'), ('21', 'Fire Breathing'), ('22', 'Freeze Time'), ('23', 'Frenzy'), ('24', 'Friend of Children'), ('25', 'Gas Refinery'), ('26', 'Giant Brain'), ('27', 'Gourmet'), ('28', 'Heal'), ('29', 'Healing Ray'), ('30', 'Herbivore'), ('31', 'Herd Culler'), ('32', 'High Altitude Bombing'), ('33', 'It Has a Child'), ('34', 'Jet Fighters'), ('35', 'Jets'), ('36', 'Made in a Lab'), ('37', 'Metamorph'), ('38', 'Mimic'), ('39', 'Monster Batteries'), ('40', 'National Guard'), ('41', 'Nova Breath'), ('42', 'Nuclear Power Plant'), ('43', 'Omnivore'), ('44', 'Opportunist'), ('45', 'Parasitic Tentacles'), ('46', 'Plot Twist'), ('47', 'Poison Quills'), ('48', 'Poison Spit'), ('49', 'Psychic Probe'), ('50', 'Rapid Healing'), ('51', 'Regeneration'), ('52', 'Rooting for the Underdog'), ('53', 'Shrink Ray'), ('54', 'Skyscraper'), ('55', 'Smoke Cloud'), ('56', 'Solar Powered'), ('57', 'Spiked Tail'), ('58', 'Stretchy'), ('59', 'Tanks'), ('60', 'Telepath'), ('61', 'Urbavore'), ('62', 'Vast Storm'), ('63', 'We are Only Making It Stronger'), ('64', 'Wings'), ('65', 'Amusement Park'), ('66', 'Army'), ('67', 'Cannibalistic'), ('68', 'Intimidating Roar'), ('69', 'Monster Sidekick'), ('70', 'Reflective Hide'), ('71', 'Sleep Walker'), ('72', 'Super Jump'), ('73', 'Throw a Tanker'), ('74', 'Thunder Stomp'), ('75', 'Unstable DNA')], max_length=2)),
                ('card_used_type', models.CharField(choices=[('1', 'KEEP'), ('0', 'DISCARD')], max_length=1)),
                ('location', models.CharField(choices=[('1', 'TOKYO'), ('0', 'OUTSIDE')], max_length=1)),
                ('victory_points', models.IntegerField()),
                ('energy_cube', models.IntegerField()),
                ('life_points', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.User')),
            ],
        ),
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField()),
                ('dice1', models.CharField(choices=[('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE'), ('4', 'ATTACK'), ('5', 'HEAL'), ('6', 'ENERGY')], max_length=1)),
                ('dice1_selected', models.CharField(choices=[('1', 'SELECT'), ('0', 'DISCARD')], max_length=1)),
                ('dice2', models.CharField(choices=[('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE'), ('4', 'ATTACK'), ('5', 'HEAL'), ('6', 'ENERGY')], max_length=1)),
                ('dice2_selected', models.CharField(choices=[('1', 'SELECT'), ('0', 'DISCARD')], max_length=1)),
                ('dice3', models.CharField(choices=[('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE'), ('4', 'ATTACK'), ('5', 'HEAL'), ('6', 'ENERGY')], max_length=1)),
                ('dice3_selected', models.CharField(choices=[('1', 'SELECT'), ('0', 'DISCARD')], max_length=1)),
                ('dice4', models.CharField(choices=[('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE'), ('4', 'ATTACK'), ('5', 'HEAL'), ('6', 'ENERGY')], max_length=1)),
                ('dice4_selected', models.CharField(choices=[('1', 'SELECT'), ('0', 'DISCARD')], max_length=1)),
                ('dice5', models.CharField(choices=[('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE'), ('4', 'ATTACK'), ('5', 'HEAL'), ('6', 'ENERGY')], max_length=1)),
                ('dice5_selected', models.CharField(choices=[('1', 'SELECT'), ('0', 'DISCARD')], max_length=1)),
                ('dice6', models.CharField(choices=[('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE'), ('4', 'ATTACK'), ('5', 'HEAL'), ('6', 'ENERGY')], max_length=1)),
                ('dice6_selected', models.CharField(choices=[('1', 'SELECT'), ('0', 'DISCARD')], max_length=1)),
                ('dice7', models.CharField(choices=[('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE'), ('4', 'ATTACK'), ('5', 'HEAL'), ('6', 'ENERGY')], max_length=1)),
                ('dice7_selected', models.CharField(choices=[('1', 'SELECT'), ('0', 'DISCARD')], max_length=1)),
                ('dice8', models.CharField(choices=[('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE'), ('4', 'ATTACK'), ('5', 'HEAL'), ('6', 'ENERGY')], max_length=1)),
                ('dice8_selected', models.CharField(choices=[('1', 'SELECT'), ('0', 'DISCARD')], max_length=1)),
                ('date_created', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.User')),
            ],
        ),
    ]
