# Generated by Django 2.2.8 on 2020-01-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('error', '1'), ('command', '1'), ('game', '1')], max_length=1)),
                ('message_string', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='dice',
            name='allowReroll',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
