# Generated by Django 2.2.6 on 2019-11-05 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice1', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Energy'), ('5', 'Attack'), ('6', 'Heal')], max_length=1)),
                ('dice1_selected', models.CharField(choices=[('Y', 'Selected'), ('N', 'Not-Selected')], max_length=1)),
                ('dice2', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Energy'), ('5', 'Attack'), ('6', 'Heal')], max_length=1)),
                ('dice2_selected', models.CharField(choices=[('Y', 'Selected'), ('N', 'Not-Selected')], max_length=1)),
                ('dice3', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Energy'), ('5', 'Attack'), ('6', 'Heal')], max_length=1)),
                ('dice3_selected', models.CharField(choices=[('Y', 'Selected'), ('N', 'Not-Selected')], max_length=1)),
                ('dice4', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Energy'), ('5', 'Attack'), ('6', 'Heal')], max_length=1)),
                ('dice4_selected', models.CharField(choices=[('Y', 'Selected'), ('N', 'Not-Selected')], max_length=1)),
                ('dice5', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Energy'), ('5', 'Attack'), ('6', 'Heal')], max_length=1)),
                ('dice5_selected', models.CharField(choices=[('Y', 'Selected'), ('N', 'Not-Selected')], max_length=1)),
                ('dice6', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Energy'), ('5', 'Attack'), ('6', 'Heal')], max_length=1)),
                ('dice6_selected', models.CharField(choices=[('Y', 'Selected'), ('N', 'Not-Selected')], max_length=1)),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_winner', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('I', 'In-Progress')], max_length=1)),
                ('num_players', models.IntegerField()),
                ('player_position', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_purchased', models.CharField(max_length=30)),
                ('card_used', models.CharField(max_length=30)),
                ('location', models.CharField(choices=[('T', 'In-Tokyo'), ('O', 'Outside-Tokyo')], max_length=1)),
                ('victory_points', models.IntegerField()),
                ('energy_cubes', models.IntegerField()),
                ('life_points', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('dice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kot.Dice')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kot.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kot.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kot.Player'),
        ),
        migrations.AddField(
            model_name='dice',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kot.Player'),
        ),
    ]
